configuration: Release

os: Visual Studio 2015 CTP

build:
  parallel: true

deploy:
- provider: NuGet
  api_key:
    secure: /Aez/maYDiX55BgGX9EkbhXBaBySsfdKifgB9SZxqySOrwtMVgPf7jOwS2XwKYJR
  skip_symbols: true
  on:
    branch: master