configuration: Release
os: Visual Studio 2015 RC
environment:
  VisualStudioVersion: 14.0
  DNX_FEED: https://www.nuget.org/api/v2
install:
  - dnvm upgrade
  - dnu restore
  - dnu pack src/Nine.Storage --configuration Release --out artifacts
  - dnu pack src/Nine.Storage.Client --configuration Release --out artifacts
  - dnu pack src/Nine.Storage.Server --configuration Release --out artifacts
  - dnx test\Nine.Storage.Client.Test test
  - dnx test\Nine.Storage.Server.Test test
build: off
artifacts:
  - path: artifacts\**\*.nupkg
